### ISSUE TITLE
"Bob"

### ISSUE THREAD

**Issue by sreikes7** [Richard2926/math_lab#3]
When I entered "Bob" for practice, I gave him 1 hour. However, it spit out 2 hours on schedule.

**Comment by Richard2926** [comment]
Hey Ms. Reikes!

So, each time slot you create, make sure they are 1/2 hour time slots. For example: When you make an entry called "10 Am - 10 30 AM" and another entry called "10 30 - 11 30 am", even though the time is an hour for one of them, they are both processed as 1/2 hour time slots. But if you also want the option to enter 1 hour time slots please let me know. I thought this would give more freedom to students. 

In this case instead of "10 30 - 11 30 am", you would add "10 30 - 11 00 am" and "11 00 - 11 30 am". 

So the reason Bob was given 2 slots is because the program was set to give him 2 1/2 hour slots or 2 entries since all entries are read as half hour slots

Thank you

**Comment by Richard2926** [comment]
Please reopen if you want me to add option to enter 1 hour time slots.

**Comment by sreikes7** [comment]
I see. So I had made the time slots on the hour. My bad. LOL. 

I might have to think on this! When I make the excel sheet, I make it on the 30 minutes. But when students sign up, I make them sign up for a full hour. I will have to get back to you on this.
